import React from "react";
import "./Sam.css";
import { Link } from "react-router-dom";


export default function Sam() {
    return (
        <section className="city-page">
            <div className="city-wrapper">

                {/* HERO */}
                <header className="city-hero">
                    <h1>Samarqand</h1>
                    <p>Samarqand — O'zbekiston Respublikasidagi 3000 ming yillik tarixga ega eng qadimiy shahardir. Samarqandni nafaqat O'zbekistonning balki butun O'rta Osiyongni yuragi ham deb atashadi.</p>
                </header>

                {/* UMUMIY MAʼLUMOT */}
                <article className="city-section">
                    <h2>Umumiy maʼlumot</h2>
                    <p>Samarqand – Oʻzbekiston Respublikasi Samarqand viloyatidagi qadimiy shahar. Amir Temur ordeni sohibi[3]. Viloyatning maʼmuriy, iqtisodiy va madaniy markazi (1938-yildan). 1925-1930-yillarda Respublika poytaxti. Oʻzbekistonning janubi-gʻarbida, Zarafshon vodiysining markaziy qismida (Dargʻom va Siyob kanallari orasida) joylashgan. Oʻrtacha 695 m balandlikda. Toshkentdan 300 km. Samarqanddan Toshkent—Dushanbe, Toshkent—Turkmanboshi, Toshkent—Uchquduq—Qoʻngʻirot temir yoʻllari, Katta Oʻzbek trakti (Toshkent—Termiz yoʻli) oʻtadi. Shahar aholisi va xoʻjaliklari Shovdor, Bogʻishamol ariqlaridan suv oladi. Iyulning oʻrtacha harorati 25,9°, eng baland harorat 40—42°, yanvar oʻrtacha harorati 0,2°, eng past harorat —26°. Maydoni −120 km². Aholisi 585 ming kishi (2024). 2022-yilning 15-16-sentyabr kunlari ShHTga aʼzo davlat rahbarlarining 22-yigʻilishi " Samarqand sammiti " boʻlib oʻtgan.</p>
                    {/* <div className="image-placeholder">Rasm joyi (Samarqand manzarasi)</div> */}
                </article>

                {/* IQLIM */}
                <article className="city-section">
                    <h2>Nomlanish tarixi</h2>
                    <p>Tarixiy yozma manbalarda Samarqand yoshi qadimiyligi haqida maʼlumotlar bor. Muhammad an-Nasafiy "al-Qand fiy zikri ulamoi , Haydar as-Samarqandiy (XII asr) „Qandiyai Xurd“, Abu Tohirxoja Samarqandiy „Samariya“, Xitoy tarixchisi Chjan Syan, yunon va rimlik tarixchilar Arrian, Kursiy Ruf va boshqa koʻplab mualliflarning asarlarida bu haqda yozib oʻtilgan. Samarqand va Rim insoniyat taqdiridagi buyuk xizmatlarini nazarda tutib „Boqiy shaharlar“ nomini olganlar. Xalq iborasi „Samarqand sayqali roʻyi zamin ast“ – Samarqand yer yuzining sayqali (jilosi) deb behuda aytilmagan. Amir Temur Samarqandni mehr bilan qadrladi, obod qildi, dunyoning sayqaliga aylantirdi.</p>
                    <p>„Samarqand“ soʻzining kelib chiqishi haqida bir qancha taxmin mavjud. Sharq mualliflari „Samarqand“ soʻzining 1-qismi, yaʼni „Samar“ soʻzi shu shaharga asos solgan yoki shaharni bosib olgan kishining nomi deb hisoblab, bir qancha sunʼiy taʼriflarni taklif etdilar, ammo tarixda bunday ismli kishi haqida maʼlumotlar aniqlanmagan. Soʻzning 2-qismi „kent“ (kand) – qishloq, shahar degan maʼnoni bildiradi. Baʼzi yevropalik olimlar, bu nom qadimdan qolgan, sanskritcha „Samarya“ra yaqin, yaʼni „yigʻilish, yigʻin“ soʻzidan kelib chiqqan deb izohlaydilar. Antik mualliflarning asarlarida shahar Marokanda deb atalgan. Bu haqiqatga ancha yaqin boʻlib, Marokanda – Samarqand atamasining yunoncha aytilishidir.</p><p>
                        XI asr olimlaridan Abu Rayhon Beruniy va Mahmud Qoshgʻariy shahar nomining kelib chiqishini „Semizkent“, yaʼni „semiz qishloq“ soʻzining buzib talaffuz qilinishi deb tushuntiradilar[4]. 1404-yilda Samarqandga tashrif buyurgan Ispaniya elchisi Ruy Gonsales de Klavixo ham bu talqinni qoʻllab quvvatlaydi[5].</p>
                    <p>Bulardan tashqari, turli davrlarda bitilgan tarixiy manba va kitoblarda shahar nomi Samariana, Saramanka, Sakanna, Sanmangan, Samakiyon, Sumron, Shamarkan, Samaroy, Simroyat kabi shakllarda ham qayd etiladi[6].</p>
                    <p>Fanda Samarqand toponimining yuzaga kelishi va semantikasi borasida turli xil fikr va mulohazalar keltirilgan. Ayrim xorijiy toponimistlar shahar nomi sanskritga samariya – „yigʻin“ yoki „anjuman“ soʻzidan olingan degan fikrni aytgan. „Tarixi Tabariy“, „Samariya“ va „Gʻiyos ul-lugʻot“ asarlarining mualliflari yozishlaricha, „Samar“- podshoning nomi boʻlib, „kand“ esa turkiy tilda „shahar“ degan maʼnoni anglatgan. Demak, Samarqand – Samar shahri demakdir.</p>
                    {/* <div className="image-placeholder">Rasm joyi (Zarafshon vodiysi)</div> */}
                </article>

                {/* NOMLANISH TARIXI */}
                <article className="city-section">
                    <h2>Qadimgi davr va Ilk oʻrta asrlar</h2>
                    <p>Samarqand jahonning eng qadimgi shaharlaridan biri – 2700-yildan ortiq tarixga ega. Samarqand miloddan avval IV asrdan milodiy VI asrgacha Sugʻd davlatining poytaxti boʻlgan. Arxeologik qazishmalardan maʼlum boʻlishicha, yuqori paleolit davrida ham Samarqand hududida odamlar yashagan (qarang Samarqand makoni).</p>
                    <p>Rim tarixchisi Kvint Kursiy Rufning (miloddan avval I asr oxiri – milodiy I asr) yozishicha, Samarqand qalʼasi devorining aylanasi taxminan 10,5 km boʻlgan. Miloddan avval 329-yil Iskandar Maqduniy (Makedonskiy) askarlari Samarqandni vayron qilgan. Spitamen Samarqandni yunonlardan ozod etishga harakat etgan, ammo xiyonatkor koʻchmanchi qabilalar sardorlari tomonidan oʻldirilgan va boshi Iskandar Maqduniyga sulh sifatida yuborilgan.</p>
                    {/* <div className="image-placeholder">Rasm joyi (Qadimiy Samarqand xaritasi)</div> */}
                </article>

                {/* QADIMGI DAVR */}
                <article className="city-section">
                    <h2>Turk xoqonligi va Gʻarbiy turk xoqonligi tarkibida</h2>
                    <p>Samarqand 6-asrda Turk xokonligi tarkibiga kirgan va mahalliy hokimlar tomonidan boshqarilgan. Bu davrda Samarqand Hindiston, Eron, Misr va Vizantiya davlatlari bilan savdo qilgan. Oʻz davrida „10 Oʻq xoqonligi“ deb yuritilgan Gʻarbiy Turk xoqonligi Istamining oʻgʻli Tardu xoqon (576—603) Sosoniylar Eroniga qarshi janglar olib borib, gʻarbda oʻz hokimiyatini kuchaytirdi. Uning oʻgʻli Sheguy xoqon (610—618) davrida xoqonlik qoʻshinlari jan.gʻarbiy hududlarda faol harakat yurita boshlaydi. U Eronning shimoliy sharqiy viloyatlariga hujum uyushtirib, sosoniylar ustidan yirik gʻalabaga erishadi. Uning inisi Tun yabgʻu (618—630) xoqonlikning gʻarbdagi nufuzini yanada mustahkamlaydi. U hukmronlik qilgan davrda Turk xoqonligining chegarasi gʻarb va janubiy gʻarbda, Janubiy-Sharqiy Yevropa dashtlari, Kavkaz, Volgaboʻyi, Gurgon, Marv, Hind daryosining yuqori havzalari, Shimoliy Hindiston va Afgʻonistonning aksariyat viloyatlarini oʻz ichiga olardi. Tun yabgʻu gʻarbiy hududlarda hokimiyatni mustahkamlash maqsadida qarorgohini Shosh vohasining shimolidagi Mingbuloq mavzesiga koʻchiradi va boshqaruvda islohotlar oʻtkazib qaram oʻlkalarga turkiy tudun va eltabar unvonli vakillar joʻnatadi.</p>
                    {/* <div className="image-placeholder">Rasm joyi (Afrosiyob qazilmalari)</div> */}
                </article>

                {/* TURK VA ARAB DAVRI */}
                <article className="city-section">
                    <h2>Arab xalifaligi tarkibida</h2>
                    <p>Qutayba ibn Muslim boshchiligidagi arab qoʻshinlari 712-yilda Samarqandni egallagan. Isyon koʻtargan shahar aholisining bir qismini qirib tashlagan. Attabariy keltirgan maʼlumotga koʻra, samarqandliklar shahriston (ichki shahar)ni arablarga boʻshatib berishga majbur boʻlganlar. Arablar shahristonda masjid va minbar qurganlar. Mahalliy aholidan tortib olingan qimmatbaho buyumlar va oltin, kumush bilan bezatilgan sanamlar (xilat ulasnom) ni eritib 10 ming misqol qimmatbaho metall olingan. Buyuk ipak yoʻli asosidagi hududlararo savdo-sotiq yanada ravnaq topdi. 776—783-yillarda arablarga qarshi Muqanna boshchiligida isyon koʻtarilgan (qarang Muqanna isyoni).</p>
                    {/* <div className="image-placeholder">Rasm joyi (Qadimiy masjidlar)</div> */}
                </article>

                {/* TEMURIYLAR */}
                <article className="city-section">
                    <h2>Somoniylar va Qoraxoniylar davri</h2>
                    <p>Arablarga qarshi koʻtarilgan isyonlarni bostirishga faol qatnashgan mahalliy zamindor aholi vakillari IX asr 20 yillaridan Movarounnahr va viloyatlarini boshqarishga tortildi, masalan, Samarqandni boshqarish Somoniylar qoʻliga oʻtdi. Oʻsha vaqtdan Samarqand – Somoniylar davlatining poytaxti boʻldi. 887-yildan birinchi marta somoniylar kumush tangalari Samarqandda zarb qilina boshladi. Somoniylar poytaxti Buxoroga koʻchirilgandan (889) soʻng ham Samarqand Movarounnahrning eng katta hunarmandchilik va savdo markazlaridan biri boʻlib qoldi. XI asrdan Samarqand Qoraxoniylar davlati tarkibiga kirgan. Qoraxoniylar davrida turli oʻlkalarning birlashishi fan va madaniyat rivojiga ham imkon berdi. Bu davrda Samarqand ham maʼmuriy, ham madaniy markaz sifatida ahamiyati oshib, yanada kengayib, rivojlanib borgan. Qoraxoniylar fan va madaniyatning oʻlka hayotidagi muhim oʻrnini anglab unga homiylik qilishgan. Buyuk ipak yoʻli asosidagi hududlararo savdo-sotiq yanada ravnaq topdi.</p>
                    <p>Shu davrda Samarqandda Ibrohim tamgachxon madrasasi va kasalxonasi bunyod etilgan.</p>
                    <p>XI asrda Samarqandda Shohi Zinda maqbarasi barpo etildi[8]. Keyinchalik xuddi shu yerga 1066-yili Tamgʻach Boʻgʻraxon madrasasi qurildi va unga tutash bir qator turkum majmua yuzaga keldi. XI-XII asrlarda serhasham bezatilgan boshqa maqbaralar vujudga kela boshladi. Arxeologlar ulardan bir nechtasini XIV asr inshoatlarining gʻarb tamonidagi yoʻlakdan qazib topdilar. Ular bezaklari bilan Temur davri maqbaralaridan farq qilgan. Oʻsha davrda ham, Qusam ibn Abbos maqbarasi „muqqadas“ hisoblanib ziyorat qilingan.</p>
                    <p>Qoraxoniylar hukmronligi davrida Umar Xayyom Samarqandga Nishopurdan Shamsalmulk saroyiga taklif qilingan. Umar Xayyom Balx va Buxoro madrasalari bilan bir qatorda Samarqand madrasalaridan birida ham tahsil olgan. Samarqandda u algebra boʻyicha asosiy asarni yozgan.</p>
                    <p>Qoraxoniylar davrida Samarqandda Oʻrta Osiyoning taniqli mutafakkiri, olimi, faylasufi, islom huquqshunosi Burhoniddin Margʻinoniy (1123-1197) yashagan.</p>
                    <p>Qoraxoniylar davrining Samarqanddagi eng koʻzga koʻringan yodgorligi – XII asrda qoʻrgʻonda qurilgan Ibrohim ibn Husayn (1178-1202) saroyi. Qazish paytida monumental rangtasvirning parchalari topildi. Sharqiy devorda sariq chapon kiygan va kamon ushlagan turkiy jangchi tasvirlangan. Bu yerda otlar, ovchi itlar, qushlar va davrga oʻxshash ayollar ham tasvirlangan</p>
                    <p>Amaliy bezak sanʼati – naqshinkorlik, ganchkorlik va kulolchilik yoʻnalishlari rivojlangan. Adabiyot yuksalgan. Yusuf Xos Hojibt\nt „Qutadgʻu bilig“, Mahmud Qoshgʻariynit „Devonu lugʻotit turk“ kabi asarlari shu davrda yaratilgan.</p>
                    <p>XI asrda Samarqandni Saljuqiylar bosib olgan. XII asrdan Qoraxitoylarga tobe boʻlgan. 1210-yildan Muhammad Xorazmshoh davlati tarkibida. 1212-yil samarqandliklar Xorazmshohga qarshi isyon koʻtargan.</p>
                    {/* <div className="image-placeholder">Rasm joyi (Registon maydoni)</div> */}
                </article>

                <article className="city-section">
                    <h2>Moʻgʻullar hukmronligi davrida</h2>
                    <p>1220-yil Chingizxon qoʻshinlari Samarqandga bostirib kirib, shaharga oʻt qoʻygan va aholining koʻp qismini qirgan, qolganlari shaharni tark etib omon qolgan. Bir necha yildan soʻng Samarqand qayta tiklana boshlagan. XIII asr 2-yarmida Samarqandga kelgan venetsiyalik sayyoh Marko Polo „Sonmarkon kapa va mashhur shahar“ deb yozgan. Moʻgʻullar hukmronligi davrida Samarqand Chigʻatoy ulusi tarkibida boʻlgan</p>
                </article>

                <article className="city-section">
                    <h2>Amir Temur va Temuriylar davrida</h2>
                    <p>XIV asr oʻrtalarida Movarounnahrda moʻgullarga qarshi xalq harakatlari boʻlib oʻtdi. Sarbadorlar isyoni natijasida shaharda bir necha oy xalq hokimiyati oʻrnatildi. XIV asr oxiri va XV asrda Samarqand iqtisodiy-siyosiy va madaniy hayoti ancha yuksaldi. Amir Temur saltanati poytaxti sifatida Samarqand jahonga mashhur boʻldi.</p>
                    <p>Saltanat poytaxti Samarqand Amir Temur davrida ayniqsa gullab yashnadi. Shaharda Isfahon, Sheroz, Halab, Xorazm, Buxoro, Qarshi va Kesh shaharlarining meʼmor va binokorlari qoʻli bilan saroylar, masjidlar, madrasalar, maqbaralar quriladi. Shahar tashqarisida esa bogʻ-rogʻlar va boʻstonlar barpo etiladi (qarang Amir Temur bogʻlari). Xususan, Shohi Zinda meʼmoriy majmuasiga mansub Shodimulk ogʻo maqbarasi, Shirinbeka ogʻo maqbarasi va boshqa quriladi. Shaharda Bibixonim jome masjidi, Amir Temurning qarorgohi Koʻksaroy va Boʻstonsaroylar qad koʻtaradi. Umuman olganda Samarqand sh. Amir Temur davrida oʻzining qad. oʻrni Afrosiyobyaan birmuncha jan.roqda butunlay yangitdan qurildi. Shahar tevaragi mustahkam qalʼa devori bilan oʻralib, Ohanin, Shayxzoda, Chorsu, Korizgoh, Soʻzangaron va Feruza kabi nomlar bilan ataluvchi 6 ta darvoza oʻrnatildi. Movarounnahrning dehqonchilik vohalarida, xususan Zarafshon vodiysida oʻnlab sugʻorish tarmoqlari chiqarilib, dehqonchilik maydonlari kengaytirildi. Yangi qishloqlar barpo etildi. Ibn Arabshohning yozishicha, Amir Temur Samarqand atrofida qad koʻtargan bir qancha yangi qishloqlarni Sharqning mashhur shaharlari Dimishq (Damashq), Misr, Bagʻdod, Sultoniya va Sheroz nomlari bilan atadi. Amir Temurning fikricha, Samarqand kattaligi, goʻzalligi hamda tevarak-atrofining obod etilganligi jihatidan dunyodagi eng yirik shaharlardan ham ustunroq turmogʻi lozim edi.</p>
                    <p>Bu davrda Samarqand koʻpgina Sharq va Yevropa davlatlari bilan savdo aloqalari oʻrnatgan. Samarqandda koʻplab hashamatli meʼmoriy inshootlar qurilgan. Yirik sharqshunos olim V. V. Bartold taʼkidlaganidek, Amir Temurning fikriga koʻra, Samarqand jahonning birinchi shahri boʻlishi kerak edi. Amir Temur vafoti (1405) dan soʻng Samarqand taxtini Ulugʻbek egalladi. Ulugʻbek davrida Samarqandda bunyodkorlik avj oldi. Qoʻshni davlatlar bilan aloqalar kuchaydi. U Oʻrta Osiyo xalqiari ilm-fani va madaniyatini oʻrta asr sharoitida dunyo fanining muayyan pogʻonasiga olib chiqsi. Uning qilgan eng katta ishi – Samarqand ilmiy maktabini oʻsha davr akademiyasini barpo etganligi boʻldi. Bu ilmiy maktabda 200 dan ortiq olimlar faoliyat olib borgan. Ular orasida eng kattalari Qozizoda Rumiy, Gʻiyosiddin Jamshid Koshiy edi. U.ning ilmiy maktabi oʻz faoliyatida oʻrta osiyolik mashhur olimlar Muhammad Xorazmiy, Ahmad al-Fargʻoniy, Abul Abbos al-Javhariy, Ibn Turk al-Xuttaliy, Xolid al-Marvarrudiy, Ahmad al-Marvaziy, Abu Nasr Forobiy, Abu Rayhon Beruniylir boshlab bergan ilmiy anʼanaga asoslanar edi. U. Samarqand yaqinida rasadxona barpo qildi.</p>
                    <p>XV asr oxirida Samarqandni Zahiriddin Muhammad Bobur egalladi (1497).</p>
                </article>

                <article className="city-section">
                    <h2>Shayboniylar va Ashtarxoniylar davrida (XVI-XVIII asrlar)</h2>
                    <p>1500-yil Shayboniyxon Samarqandni deyarli urushsiz bosib oldi. XVI asr oʻrtalarigacha Samarqand Shayboniylar davlatining poytaxti boʻlib turdi. Oʻsha vaqtdan rus bosqiniga qadar (1868) Buxoro amirligi tarkibida edi.</p>
                    <p>Shayboniylar daxmasi – Samarqanddagi oʻrta asr meʼmoriy yodgorligi (16-asr). Shayboniyxon 1510-yilda Ismoil I Safaviy bilan boʻlgan jangda halok boʻlgach, Samarqandga olib kelinib oʻzi qurgan madrasada marmar supa ostiga dafn etilgan. Supa ostiga Shayboniyxondan tashqari boshqa shayboniy sultonlar va malikalar: Mahmud Sulton (1503—04 y. oʻldirilgan), Mahdiy sulton, Hamza Sulton (1511-yil oʻldirilgan), Muhammad Temur Sulton (1511-yil v.e.), Qutlugʻ Muhammad Sulton (1545-yil v.e.), Abulxayr Sulton (1511-yil udsirilgan), Yodgor Sultonim (1526-yil v.e.), Shaxribonu xonim (1535-yil v.e.), Shoh Sulton xonim (1530-yil v.e.), Suyunch Muhammad Sulton (1586-yil v.e.) lar dafn etilgan.</p>
                    <p>Ashtarxoniy Imomqulixon davrida (1611-1642) Samarqandda mashhur meʼmorchilik durdonalari qurilgan. Shuningdek, ushbu davrda Samarqandning hozirgi kunda saqlanib kelayotgan yodgorliklaridan Abdi Berun ansambli barpo etildi.</p>
                    <p>Registon ansamblida Ulugʻbek davrida bunyod etilgan Mirzoyi karvonsaroyi (15-asr) oʻrnida Samarqand hokimi Yalangtoʻshbiy Bahodir Madrasa va jome masjid qurdirgan (1641—1646). Karvonsaroy asosi ustiga Madrasa (shim. sharqiy qismida), hujralar oʻrnida peshtoq gumbazli masjid (gʻarbida) joylashgan. Dastlab „Yalangtoʻshbiy kichik madrasasi“ deb nomlangan. Keyinchalik masjid bezagida boshqa bir obida qurilishiga yetadigan miqdorda oltin sarflangani uchun „tillakori“ (tilladan ishlov berilgan) deb yuritila boshlagan. Tilla Qori madrasasidan shahar jome masjvdi va Madrasa sifatida foydalanilgan. Peshtoq ravogʻidagi marmar taxtachada bezak ishlari 1659—60 yillarda bajarilganligi yozilgan.</p>
                    <p>Mirzo Ulugʻbek xonaqohi oʻrniga Yalangtoʻsh Bahodir Sherdor madrasasini (1619—36) qurdirgan. Ulugʻbek madrasasining roʻparasida joylashgan</p>
                    <p>Samarqandga oʻzbek adabiyotining shoiri va mutafakkiri, naqshbandiylar tariqati vakili Boborahim Mashrab (1657-1711) ham tashrif buyurgan.</p>
                    <p>1723—1730-yillarda qozoklar bosqini davrida katta talofat koʻrdi. 1740—1747-ylarda Nodirshohga tobe boʻldi. XVII asrning 1-yarmida olchin urugʻidan chiqqan oʻzbek harbiy zamindorlarining katta vakili Yalangtoʻsh Bahodir Samarqand hokimi boʻlgan. 1758—1868-yillarda esa Samarqand Buxoro amirligiga itoat qilgan.</p>
                </article>

                <article className="city-section">
                    <h2>Buxoro amirligi davrida (1756-1868)</h2>
                    <p>Amir Shohmurod (1785—1800) davrida Samarqandda koʻplab madrasalar, masjidlar va turli binolar qurilgan. Xususan, Zarafshon vodiysidagi dehqonchilikka katta eʼtibor qaratilib, Zarafshon daryosidan turli ariqlar (Qozonariq, Toyman arigʻi, Toʻgʻuzariq). Oqdaryo va Qoradaryodan yangi ariqlar chiqarilgan hamda boshqa sugʻorish inshootlari qurilgan. shahrining oʻzi Samarqandni qayta qurish tarkini chizgan. Sh. shaharda 24 ta mavze qurib, mamlakatning sharqiy viloyatlaridan bu yerga aholini koʻchirib keltirgan.</p>
                    <p>1841—1842-yillarda Buxoroga Rossiya elchisi qilib yuborilgan sharqshunos N. V. Xanikovning yozishicha, oʻsha vaqtda Samarqand baland devor bilan oʻralgan boʻlib, uning 6 ta darvozasi: Buxoro, Paykobod, Shohizinda, Qalandarxona, Soʻzangaron, Xoja Ahror boʻlgan. Kechalari shaharga kiribchiqish taqiqlangan. Shahar devorining aylanasi 13,9 km, uning umumiy maydoni esa 10,4 km²ni tashkil qilgan. Shaharda juda koʻp bogʻ, ariqzovur va hovuzlar, ikkita gʻishtin karvonsaroy va uchta hammom (2 tasi Xoja Axror hammomlari, bittasi Miri hammomi) faoliyat koʻrsatgan. Koʻchalar shaharning 6 ta darvozasini Registon maydoni bilan bogʻlagan. Bibixonim masjidi bilan Chorsu oʻrtasidagi koʻcha ancha serqatnov boʻlgan. Qoʻrgʻon shaharning gʻarbiy qismida boʻlib, uning uz. 3,2 km li tashqi devori va ikkita darvozasi boʻlgan. Qoʻrgʻonda hokim saroyi, sipohilar yashaydigan uylar joylashgan. Shahar aholisining soni 25—30 mingga yetgan.</p>
                </article>

                <article className="city-section">
                    <h2>Rossiya imperiaysi tarkibida</h2>
                    <p>1868-yil 1-mayda Samarqand yaqinidagi Choʻponota tepaligida rus podshohi qoʻshinlari bilan samarqandliklar oʻrtasida qattiq jang boʻldi. Samarqand aholisi shaharni bosqinchilardan mardonavor himoya qildilar. Nihoyat, ruslar katta talofatlar berib shaharni 2-mayda egalladilar. Keyinchalik Samarqand va Kattaqoʻrgʻon bekliklari birlashtirilib, Zarafshon okrugi tuzildi. Soʻngra unga Panjakent va Zarafshon vodiysi yuqorisidagi togʻli rayonlar ham qoʻshildi. 1886-yil Zarafshon okrugi Samarqand viloyatiga aylantirildi. Samarqand uning maʼmuriy va savdo markaziga aylandi. Oʻsha vaqtdan boshlab, shaharda yangi tipdagi binolar kurila boshladi, yangi sanoat korxonalari qad koʻtardi.</p>
                    <p>Samarqand yevropacha tipdagi qismini qurish ishlari 1871-yilda boshlandi. Oʻsha vaqtda okrug gubernatori general Abramovning buyrugʻiga muvofiq, mahalliy aholining yer uchastkalari musodara qilinib va sotib olinib, ofitserlar hamda amaldorlarga, kichik harbiy lavozimdagi oilali kishilarga, va, mustasno tariqasida, rus savdogarlari hamda meshchanlarga boʻlib berilgan. Kichik lavozimdagi harbiylarga „Soldatskaya slobodka“ deb ataluvchi shimoli-gʻarbiy buluk ajratilgan. Oʻsha davrda Eski va Yangi shahar oʻrtasida xiyobon va bogʻ barpo etildi, harbiy gubernator uyi, kazarmalar, ofitserlar majlis oʻtkazadigan bino quriddi. Podsho Rossiyasi mustamlakachiligi davrida Sda bir nechta kayta ishlovchi mayda korxonalar vujudga keldi. Shaharda 34 paxta tozalash, 20 vino, bir necha spirt, pivo zavodlari, tegirmonlar ishlagan. Metallni kayta ishlash zavodida bir qancha presslash, 2 ta yoʻnuvchi, 2 ta vint kesish stanogi boʻlib, choʻyan buyumlar, zanjir, oʻroq, panshaxa, ketmon, bolta kabi buyumlar ishlab chikarilgan.</p>
                    <p>XX asr boshiga kelib Samarqanddagi korxonalar, temir yoʻl ustaxonalarida ishchilar soni koʻpaydi. 1917-yil 5-dekabrda Samarqandda hokimiyat shoʻrolar qoʻliga oʻtdi. 1918-yil 11-aprelda Samarqandda shoʻrolarning viloyat sʼyezdi boʻlib, sʼyezdda Turkiston Muxtor Respublikasi tuzilishi eʼlon qilindi. 1925—30 yillarda Samarqand Oʻzbekiston poytaxti boʻlib turdi. 1991-yil Oʻzbekiston mustaqillikka erishgach, Samarqand respublikaning katta madaniy markaziga aylandi.</p>
                </article>

                <article className="city-section">
                    <h2>Samarqandni oʻrganilishi va tadqiqi</h2>
                    <p>Samarqandni arxeologik jihatdan oʻrganish ishlari XIX asr oxirlarida boshlangan edi. 1895-yilda sharqshunos olim V. V. Bartoldning tashabbusi bilan tuzilgan „Turkiston arxeologiya havaskorlari toʻgaragi“ aʼzolari Samarqanddagi Afrosiyobni koʻp asrlar xazinasi deb qarab, unda keng koʻlamdagi arxeologik qazishma ishlarini olib bordilar. Vasiliy Vyatkin, N. I. Veselovskilar oʻtkazgan arxeologik qazishmalar natijasida turli xildagi qadimiy buyumlar topilib muzeyga berildi. 1908-yilda V. L. Vyatkin Samarqand chekkasida joylashgan Ulugʻbek rasadxonasining oʻrnini aniqladi va qazish ishlarini oʻtkazdi. Natijada rasadxona harobasi hamda uning yer ostidagi butun qolgan qismi qazib ochildi. Oʻsha davrdan boshlab Oʻrta Osiyo xalqlarining qad. madaniy merosini oʻrganishda dastlabki qadamlar qoʻyildi. 1912—1913, 1929—1930-yillarda V. L. Vyatkin, 1912-yil M.Ye. Masson Afrosiyobda qazish ishlarini olib bordilar. A. I. Terenojkin 1945—1948-yillarda S 2500-yillik tarixga ega deb belgiladi; shahar tarixi davrlashtirildi.</p>
                    <p>1950-yillardan boshlab Afrosiyobda muntazam arxeologik qazishmalar oʻtkazish, ayniqsa, 1958-yildan V. A. Shishkin rahbarligida, 1966-yildan boshlab esa Ya. Gʻ.Gʻulomov boshchiligida faollashdi. Afrosiyobni oʻrganish ishlari koʻlamini kengaytirish maqsadida, 1966-yilda doimiy harakatdagi Afrosiyob kompleks arxeologiya ekspeditsiyasi tashkil etildi. 1970-yilda Samarqandda Oʻzbekiston Fanlar akademiyasining mustaqil Arxeologiya instituti tashkil etilishi Samarqanddagi arxeologik qazishmalarni yanada keng koʻlamda olib borishga imkoniyat yaratdi. Arxeologik qazishmalar natijasida Samarqandning yoshi aniqlandi va 1970-yilda shaharning 2500-yillik yubileyi keng nishonlandi. 1971—1977-yillarda Sh. Toshxoʻjayev, 1978—1985-yillarda G. V. Shishkina qazishma ishlarini olib bordilar. Mustaqillik yillarida arxeologik qazish va ilmiy tadqiqot ishlarining samaradorligini oshirish maqsadida fransiyalik akademik, sharqshunos arxeologlar Pol Bernar va Frans Grene, oʻzbek arxeolog olimlari prof. M. Isomiddinov, A.Anorboyev va tadqiqotchi A. Otaxoʻjayevlar bilan hamkorlikda ishladilar. Natijada, Afrosiyobdagi eng quyi madaniy qatlamlarni oʻrganish jarayonida yer sathidan 10-15 metr chuqurlikda miloddan avval IX—VII asr oʻrtalariga oid ashyolar topildi. Bular qoʻlda yasab rangli naqsh berilgan sopol idishlarning parchalari va shuningdek, guvaladan tiklangan 7 metr qalinlikdagi mudofaa devori qoldiklaridir. Afrosiyobning 19 gektarlik ark qismi devor bilan butunlay oʻrab olingan. Afrosiyobning boshqa joylari ham tekshirib koʻrilganda quyi qatlamlaridan shunga oʻxshash va miloddan avval IX—VII asrlarga oid ashyolar topildi.</p>
                    <p>Afrosiyobdan topilgan ushbu namunalar Fransiyada radiokarbon tadqiqot usulida oʻrganilib, ular miloddan avval VII asrga, aniqrogʻi 2750 yoshga taalluqliligi isbotlandi.</p>
                    <p>Samarqand bunyod boʻlganidan buyon u Oʻrta Osiyoning siyosiy, iqtisodiy va madaniy hayotida katta mavqega ega boʻlib keldi. Shaharning Buyuk ipak yoʻli chorrahasida joylashganligi, bu yerda qadimdan hunarmandchilikning shoyi toʻqish, mashhur Samarqand qogʻozi ishlab chiqarish, kulolchilik, temirchilik, novvoylik, qandolatchilik, badiiy kashtachilik va boshqa turlari hamda savdosotiq ishlarining rivojiga turtki boʻldi. Samarqandda qadimdan ravnaq topgan hunarmandchilik turlari mahallaguzarlarning nomlarida saqlanib qolgan, mas. „Soʻzangaron“ (igna tayyorlovchilar), „Kamongaron“ (oʻqyoy yasovchilar) va boshqa nomlar hozirgi kungacha yetib kelgan.</p>
                    <p>Samarqand – aholisining soni va sanoatining koʻlami boʻyicha Oʻzbekistonda yetakchi oʻrinlardan birida. 1930-yil larda pillakashlik va shoyi toʻqish fabikalari, meva konserva zavodi, choy qadoqlash fabrikasi qurildi. 1940—1970-yillarda Samarqandda „Krasniy dvigatel“, „Kinap“, tamakifermentatsiya zavodlari, yigiruv fabrikasi, superfosfat zavodi, poyabzal va tikuvchilik fabikalari, uysozlik kombinati, chinni zavodi va boshqa korxonalar qurib ishga tushirildi.</p>
                </article>

                {/* YAKUNIY */}
                <article className="city-section">
                    <h2>Zamonaviy Samarqand</h2>
                    <p>Bugungi kunda Samarqand Oʻzbekistonning yirik turistik,
                        madaniy va sanoat markazlaridan biri hisoblanadi.
                        2024-yil holatiga koʻra shahar aholisi 585 ming kishidan oshgan.</p>
                    <p>Samarqand 2022-yilda Shanxay hamkorlik tashkiloti sammitiga mezbonlik qilgan
                        va xalqaro miqyosda yana bir bor eʼtibor markaziga aylangan.</p>
                    <div className="image-placeholder">Rasm joyi (Zamonaviy Samarqand)</div>
                </article>

                <Link to="./regions/Sam_ob" className="heritage-btn">
                    Samarqandning tarixiy obidalari
                </Link>
            </div>
        </section>
    );
}
